
CPP := /Users/silentvoice/clang+llvm-3.6.2-x86_64-apple-darwin/bin/clang++


ALL : test.cpp
	$(CPP) -g --std=c++14 test.cpp -o test


.PHONY : clean


clean :
	rm -rf ./test
	rm -rf ./test.dSYM
	rm -rf ./out
